[package]
name = "fp-evm"
version = "0.8.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Primitive EVM abstractions for Substrate."
license = "Apache-2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { git = "https://github.com/selendra/substrate.git", branch = "master", default-features = false }
sp-std = { git = "https://github.com/selendra/substrate.git", branch = "master", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
evm = { git = "https://github.com/joshorndorff/evm.git", branch = "joshy-update", default-features = false, features = ["with-codec"] }
impl-trait-for-tuples = "0.1"

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-std/std",
	"serde",
	"codec/std",
	"evm/std",
	"evm/with-serde",
]
